SportsStore.Web/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Web.Models.Domain;

namespace SportsStore.Web.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart _cart;

        public CartSummaryViewComponent(Cart cart)
        {
            _cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

SportsStore.Web/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Web.Models.Domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportsStore.Web.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IProductRepository repository;

        public NavigationMenuViewComponent(IProductRepository repo)
        {
            repository = repo;
        }

        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            IEnumerable<string> categories = repository.Products
                                    .Select(x => x.Category)
                                    .Distinct()
                                    .OrderBy(x => x);
            return View(categories);
        }
    }
}

SportsStore.Web/Controllers/ProductController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using SportsStore.Web.Models.Domain;
using SportsStore.Web.Models;
using SportsStore.Web.Models.ViewModels;

namespace SportsStore.Web.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository _repo;
        public int PageSize = 4;

        public ProductController(IProductRepository repo)
        {
            _repo = repo;
        }


        public ViewResult List(string category, int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = _repo.Products
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductID)
                .Skip((page - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                        _repo.Products.Count() :
                        _repo.Products.Where(e => e.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            Product prod = _repo.Products
                .FirstOrDefault(p => p.ProductID == productId);
            if (prod != null)
            {
                return File(prod.ImageData, prod.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

SportsStore.Web/Views/Shared/EditProduct.cshtml
@model Product
 
<input type="hidden" asp-for="ProductID" />
<div class="mb-3">
    <label class="form-label">Name</label>
    <input class="form-control" asp-for="Name" />
</div>
<div class="mb-3">
    <label class="form-label">Description</label>
    <textarea class="form-control" asp-for="Description"></textarea>
</div>
<div class="mb-3">
    <label class="form-label">Category</label>
    <input class="form-control" asp-for="Category" />
</div>
<div class="mb-3">
    <label class="form-label">Price</label>
    <input class="form-control" asp-for="Price" />
</div>

<div class="actionButtons">
    <input class="btn btn-warning" type="submit" value="Save" />
    <a class="btn btn-secondary" asp-action="Index">Cancel</a>
</div>

SportsStore.Web/Views/Shared/ProductSummary.cshtml
@model SportsStore.Web.Models.Domain.Product

<div class="card mt-3">
    <div class="card-content">
        @if (Model.ImageData != null)
        {
            <div class="pull-left" style="margin-right: 10px">
                <img class="img-thumbnail" width="75" height="75"
                     src="@Url.Action("GetImage", "Product",
                new { Model.ProductID })" />
            </div>
        }

    <header class="is-flex is-justify-content-space-between is-align-items-center mb-3">
        <h4>@Model.Name</h4>

        <span class="tag is-info">
           @Model.Price.ToString("c")
        </span>
    </header>
    <div class="is-flex is-justify-content-space-between is-align-items-center">
        @Model.Description
        <form id="@Model.ProductID" asp-page="/Cart" method="post">
            <input type="hidden" asp-for="ProductID" />
            <input type="hidden" name="returnUrl"
                   value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <button type="submit" class="button is-success">Add To Cart</button>
        </form>

    </div>
    </div>
</div>

SportsStore.Web/Views/Shared/_AdminLayout.cshtml
@{
    var flashMessage = ViewBag.Message?.ToString();
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SportsStore</title>
    <link rel="stylesheet" href="/lib/twitter-bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="/lib/font-awesome/css/all.min.css" />
</head>
<body>
    <div class="bg-info text-white p-2">
        <span class="navbar-brand" ml-2>SPORTS STORE</span>
    </div>
    <div class="container m-1 p-1">
        @if (flashMessage != null)
        {
            <div class="alert alert-success alert-dismissible fade show my-3">
                @flashMessage
            </div>
        }
        @RenderBody()
    </div>
</body>
</html>

SportsStore.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SportsStore</title>

    <link rel="stylesheet" href="/lib/bulma/css/bulma.min.css" />
    <link rel="stylesheet" href="/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="/Content/styles.css" />
</head>
<body>
    <header class="has-background-primary has-text-white p-2">
        <div class="is-flex is-justify-content-space-between">
            <span>SPORTS STORE</span>
            <vc:cart-summary />    
        </div>
    </header>
    <div class="columns m-1 p-1">
        <div id="categories" class="column is-one-third">
            <vc:navigation-menu />
        </div>
        <div class=" column">
            @RenderBody()
        </div>
    </div>
</body>
</html>