SportsStore.Web/Models/Domain/Cart.cs
using System.Collections.Generic;
using System.Linq;

namespace SportsStore.Web.Models.Domain
{
    public class Cart
    {
        public virtual void AddItem(Product product, int quantity)
        {
            CartLine line = Lines
                .Where(p => p.Product.ProductID == product.ProductID)
                .FirstOrDefault();

            if (line == null)
            {
                Lines.Add(new CartLine
                {
                    Product = product,
                    Quantity = quantity
                });
            }
            else
            {
                line.Quantity += quantity;
            }
        }

        public virtual void RemoveLine(Product product)
        {
            Lines.RemoveAll(l => l.Product.ProductID == product.ProductID);
        }

        public decimal ComputeTotalValue()
        {
            return Lines.Sum(e => e.Product.Price * e.Quantity);

        }
        public virtual void Clear()
        {
            Lines.Clear();
        }

        public List<CartLine> Lines { get; set; } = new List<CartLine>();

    }

    public class CartLine
    {
        public int CartLineID { get; set; }
        public Product Product { get; set; }
        public int Quantity { get; set; }
    }
}

SportsStore.Web/Pages/Cart.cshtml.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SportsStore.Web.Models.Domain;

namespace SportsStore.Web.Pages
{
    public class CartModel : PageModel
    {
        private IProductRepository repository;
        
        public CartModel(IProductRepository repo, Cart cartService)
        {
            repository = repo;
            Cart = cartService;
        }
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }
        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }
        public IActionResult OnPost(long productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);

            Cart.AddItem(product, 1);
            
            return RedirectToPage(new { returnUrl = returnUrl });
        }

        public IActionResult OnPostRemove(long productId, string returnUrl)
        {
            var p = Cart.Lines.First(cl => cl.Product.ProductID == productId).Product;
            
            Cart.RemoveLine(p);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

SportsStore.Web/Pages/Cart.cshtml
@page
@model SportsStore.Web.Pages.CartModel

<h2>Your cart</h2>
<table class="table is-striped is-fullwidth">
    <thead>
        <tr>
            <th>Quantity</th>
            <th>Item</th>
            <th class="has-text-right">Price</th>
            <th class="has-text-right">Subtotal</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var line in Model.Cart.Lines)
        {
            <tr>
                <td class="has-text--centered">@line.Quantity</td>
                <td class="has-text-left">@line.Product.Name</td>
                <td class="has-text-right">@line.Product.Price.ToString("c")</td>
                <td class="has-text-right">
                    @((line.Quantity * line.Product.Price).ToString("c"))
                </td>
                <td>
                    <form asp-page-handler="Remove" method="post">
                        <input type="hidden" name="ProductId" value="@line.Product.ProductID" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <input type="submit" value="Remove" class="button is-small is-danger" />
                    </form>
                </td>
            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3" class="has-text-right">Total:</td>
            <td class="has-text-right">@Model.Cart.ComputeTotalValue().ToString("c")</td>
            <td></td>
        </tr>
    </tfoot>
</table>
<p class="has-text-centered">
    <a class="button is-large is-primary mr-3" href="@Model.ReturnUrl">Continue shopping</a>
    <a class="button is-large is-primary" asp-page="/Orders/Checkout">Checkout Now</a>
</p>

SportsStore.Web/Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>SportsStore</title>

    <link rel="stylesheet" href="/lib/bulma/css/bulma.min.css" />
    <link rel="stylesheet" href="/lib/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="/Content/styles.css" />
</head>
<body>
    <header class="has-background-primary has-text-white p-2">
        <span>SPORTS STORE</span>
    </header>
    <div class="container">
        @RenderBody()
    </div>
</body>
</html>